const genres = [
  "Action and Adventure",
  "Anthology",
  "Art",
  "Autobiography",
  "Biography",
  "Business",
  "Children's",
  "Classic",
  "Comic Book",
  "Coming-of-Age",
  "Cookbook",
  "Crime",
  "Diary",
  "Dictionary",
  "Drama",
  "Dystopian",
  "Economics",
  "Education",
  "Encyclopedia",
  "Engineering",
  "Essay",
  "Fantasy",
  "Fiction",
  "Folklore",
  "Graphic Novel",
  "Health",
  "Historical Fiction",
  "History",
  "Horror",
  "How-to",
  "Humor",
  "Journal",
  "Law",
  "Legend",
  "Literary Fiction",
  "Magic Realism",
  "Manual",
  "Mathematics",
  "Medical",
  "Memoir",
  "Motivational",
  "Music",
  "Mystery",
  "Mythology",
  "Narrative",
  "Non-Fiction",
  "Paranormal",
  "Personal Development",
  "Philosophy",
  "Photography",
  "Poetry",
  "Political",
  "Programming",
  "Psychology",
  "Reference",
  "Religion",
  "Romance",
  "Satire",
  "Science",
  "Science Fiction",
  "Self-Help",
  "Short Story",
  "Sociology",
  "Spirituality",
  "Sports",
  "Supernatural",
  "Technology",
  "Textbook",
  "Thriller",
  "Travel",
  "True Crime",
  "Utopian",
  "War",
  "Western",
  "Women's Fiction",
  "Young Adult",
  "Adventure",
  "Animals",
  "Astronomy",
  "Botany",
  "Cartography",
  "Crafts",
  "Dance",
  "Design",
  "DIY",
  "Education Theory",
  "Epic",
  "Ethics",
  "Fashion",
  "Feminism",
  "Folklore Studies",
  "Gardening",
  "Genealogy",
  "Geography",
  "Geology",
  "Linguistics",
  "Logic",
  "Media Studies",
  "Mythical Creatures",
  "Nature",
  "Paleontology",
  "Parenting",
  "Pets",
  "Pharmacology",
];

export default genres;
